tasks:
  - init: echo "Replace me with a build script for the project."
    command: redis-server
image:
  file: .gitpod.Dockerfile
ports:
- port: 6379
  onOpen: ignore
vscode:
  extensions:
    - abusaidm.html-snippets@0.2.1:7b7Vkkp6Lem9WOqKCYMq2w==
    - Zignd.html-css-class-completion@1.19.0:b3YWQQIEP1z3u93nyLX0UA==
